### ISSUE TITLE
Missing .gitmodules file

### ISSUE THREAD

**Issue by cash** [Cloud-CV/visual-chatbot#1]
The instructions say to run `git submodule init` but there is no .gitmodules file in the repository.

**Comment by deshraj** [comment]
@cash thanks for reporting. Updated the README https://github.com/Cloud-CV/visual-chatbot/commit/1322284fb44a38357b10ef2014bad4ad7bf7aa6c. :)

**Comment by cash** [comment]
Thanks for the quick response.
Your download models script assumes there is a directory named neuraltalk2 which I assumed was a gitmodule. Is that not true?

**Comment by deshraj** [comment]
Sorry, my bad. I have fixed it by adding the neuraltalk2 as a submodule.
