### ISSUE TITLE
The chat interface of visual dialog on this page: https://visualdialog.org/ is not working.

### ISSUE THREAD

**Issue by divyanshj16** [Cloud-CV/visual-chatbot#10]
It generates the caption very well but after asking the question it doesn'r replies back.
![image](https://user-images.githubusercontent.com/16683472/46579650-9793f880-ca33-11e8-97fe-453722f21fe3.png)
It is stuck at this place.

**Comment by ShyamPandya** [comment]
Hi, I'd like to work on this issue and contribute to the repo. Can anyone guide me in starting the same?

**Comment by deshraj** [comment]
Closing this issue since it's back up.
