### ISSUE TITLE
Image having text, digits

### ISSUE THREAD

**Issue by Shekharrajak** [Cloud-CV/visual-chatbot#16]
It is amazing to see that how beautifully Visual-chatbot is capable of answering the questions.

Can we expect answer for the questions related to the text present in image? I tried it but it looks like bot was able to tell about colors but not about the text and digits. Just curious to know.

Thanks!
Shekhar

**Comment by yashkant** [comment]
Hi @Shekharrajak, 

Visual-Chatbot currently is not capable of answering over texts in the images, which requires the use of an OCR module. You can take a look TextVQA work here: https://textvqa.org
