### ISSUE TITLE
unable to download hre-qih-g-new.t7 

### ISSUE THREAD

**Issue by gp1702** [Cloud-CV/visual-chatbot#9]
I am unable to download the the hre-qih-g-new.t7 model used in this demo. Is a new model available for running this demo ? When I try downloading I get the following error:

Resolving computing.ece.vt.edu (computing.ece.vt.edu)... 128.173.88.40
Connecting to computing.ece.vt.edu (computing.ece.vt.edu)|128.173.88.40|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2018-09-24 23:04:29 ERROR 404: Not Found.

**Comment by deshraj** [comment]
Hi @gp1702, thanks for opening this issue. We recently moved the data from one server to another and forgot to update it in the repository. I have updated the master branch (see https://github.com/Cloud-CV/visual-chatbot/commit/65ceb1d2ec4ad21b0c85d87974c0c30ef12db021) and this issue should be fixed now.
